spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/postman_db
    username: postgres
    password: postgres
  mail:
    properties:
      "[mail.debug]": false